apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: {{ name }}
  description: Microserviço Python gerado via Backstage
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: {{ owner }}
  lifecycle: experimental
